# Create a dockerfile with node image as base image
FROM node:14.17.0-alpine3.13

# Create a directory to hold the application code inside the image, this will be the working directory for your application
# call the directory /app
RUN mkdir -p /app

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install npm 
RUN npm i

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run Nodeserver.js when the container launches
CMD ["node", "nodeserver.js"]

# Write a docker comand to build the image and tag it as mynodeapp
# docker build -t mynodeapp .

# write a docker command that runs this built image
# docker run -p 3000:3000 mynodeapp